# -*- coding: utf-8 -*-
"""speech to text .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-8QksMzpOnHu2J6d4PrYVLoWjQmOft1
"""

pip install transformers

from transformers import pipeline
import transformers
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np
import transformers

print(transformers.__version__)

import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np

tokenizer=Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model=Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

audio,sampling_rate = librosa.load('speech.wav',sr=16000)
audio,sampling_rate

display.Audio('speech.wav',autoplay=True)

input_values=tokenizer(audio,return_tensors="pt").input_values
input_values

logits= model(input_values).logits
logits

predicted_ids=torch.argmax(logits,dim=-1)
predicted_ids

transciptions=tokenizer.decode(predicted_ids[0])
transciptions